package server.model;

import common.FileDTO;
import org.hibernate.annotations.NaturalId;

import javax.persistence.*;
import java.util.Date;

/**
 * Defines the file for the db
 */
@Entity
public class File implements FileDTO {

    /**
     * defines id, it is autogenerated
     */
    @Id
    @GeneratedValue
    private int id;

    /**
     * defines owner as a User, many to one relation
     * many files are owned by one user
     */

    @ManyToOne
    private User owner;

    /**
     * Define the file name as a natural id
     */
    @NaturalId
    private String name;

    /**
     * If the file is private or not
     */
    private boolean privateAccess;

    /**
     * If there is a general permission to read the file
     */
    private boolean readPermission;

    /**
     * If there is a general permission to write (overwrite) the file
     */
    private boolean writePermission;

    /**
     * The "size" of the file
     */
    private long dimension;

    /**
     * the date the "file" was added to the db
     */
    private Date createdAt;

    /**
     * the date the "file" was last updated
     */
    private Date updatedAt;

    /**
     * File constructor, defines all values for a file
     * @param owner             the owner of the file
     * @param name              the file's name
     * @param privateAccess     if the file is private
     * @param writePermission   if there is a general write permission
     * @param readPermission    if there is a general read permission
     * @param size              file "size" as a representation of its actual size
     */
    public File ( User owner, String name, boolean privateAccess, boolean writePermission, boolean readPermission, long size ) {
        this.owner = owner;
        this.name = name;
        this.privateAccess = privateAccess;
        this.readPermission = readPermission;
        this.writePermission = writePermission;
        this.dimension = size;
    }

    /**
     * Empty constructor
     */
    public File() {
    }

    /**
     * On creation we define created and updated at
     */
    @PrePersist
    private void onCreate() {
        this.createdAt = new Date();
        this.updatedAt = new Date();
    }

    /**
     * If we update the file, update updatedat time
     */
    @PreUpdate
    private void onUpdate() {
        this.updatedAt = new Date();
    }

    /*
     * Getters for all fields are found below
     */

    public int getId() {
        return id;
    }

    public User getOwner() {
        return owner;
    }

    public String getName() {
        return name;
    }

    public void setName (String name) {
        this.name = name;
    }

    public boolean hasPrivateAccess() {
        return privateAccess;
    }

    public boolean hasReadPermission() {
        return readPermission;
    }

    public boolean hasWritePermission() {
        return writePermission;
    }

    public long getDimension() {
        return dimension;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }
}
